### PR TITLE
Added searching functionality

### PR DESCRIPTION
**Pull request by ZhuoyangM**
Able to search by one field (company/position/status/location), press enter to search;
Need to clear the search box and press enter (or reload) to restore the default list.

### CODE REVIEW

**Comment by PierreBeur** [comment]
It seems that this pull request has some very serious merge conflicts that need to be resolved before it can be merged.

**Comment by ZhuoyangM** [comment]
Yes please. Also working on it!

**Comment by PierreBeur** [comment]
Merge conflicts are resolved, but this branch still has serious issues.

**Comment by ZhuoyangM** [comment]
Thank you for solving those merge conflicts! I'll try fix the rest problems.

**Comment by PierreBeur** [comment]
Just fixed the rest of the problems with the database.

**Comment by PierreBeur** [comment]
This branch is in much better shape but the search feature still needs work.

**Comment by ZhuoyangM** [comment]
Now it's able to search by typing

**Review by PierreBeur — APPROVED** [review]

**Review by JessalynWang — APPROVED** [review]

**Pull request merged**
